import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-off-black">
        <h1 className='bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 inline-block text-transparent bg-clip-text'>
          CyclopPanda
        </h1>
      </main>
    </>
  )
}
